

SET(CMAKE_INSTALL_PREFIX /home/chuck/usr)
#SET(CMAKE_CXX_COMPILER /scratch/usr/bin/g++)

SET(BOOST_ROOT /usr)
SET(BOOST_INCLUDE_DIR /usr/include)
SET(BOOST_LIBRARY_DIR /usr/lib)

SET(Boost_NO_SYSTEM_PATHS ON)

set(Boost_USE_STATIC_LIBS ON)
set(Boost_USE_MULTITHREADED ON)
set(Boost_USE_STATIC_RUNTIME ON)




