
export CPATH=/usr/include:$HOME/usr/include:$HOME/Programming/C++/external/PhysX/Include


export LPATH=/usr/lib:/usr/lib32:/usr/lib/x86_64-linux-gnu:$HOME/usr/lib

export LD_LIBRARY_PATH=/usr/lib:/usr/lib32:/usr/lib/x86_64-linux-gnu:$HOME/usr/lib

export LIBRARY_PATH=/usr/lib:$HOME/usr/lib:$HOME/physx-3.3.1_linux_sdk_core/Libs

export PYTHONPATH=/usr/lib:/usr/lib/python:/usr/lib/python2.6/site-packages:/usr/lib64/python2.6/site-packages
export PYTHONPATH=$HOME/usr/lib/python:$HOME/usr/lib/python2.6/site-packages:${PYTHONPATH}
export PYTHONPATH=$HOME/usr/lib64/python2.6/site-packages:${PYTHONPATH}
export PYTHONPATH=$HOME/git/python/Modules:${PYTHONPATH}

export PATH=/usr/bin:$PATH
export PATH=${PATH}:$HOME/usr/bin:${HOME}/git/python/bin

export CMAKE_PREFIX_PATH=$HOME/usr:/usr:/usr/local
export CMAKE_MODULE_PATH=$HOME/usr:/usr:/usr/local/lib/x86_64-linux-gnu/cmake:/usr/local

export TCLLIBPATH=$HOME/usr/lib
export ITCL_LIBRARY=$HOME/usr/lib/itcl3.4


